/*
 Script Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories

*/


-- magnitude analysis
-- compare the measures values by categories
-- helps us understand the importance of different categories


--- find total customers by countries
--- find total customers by gender
--- find total products by categories
--- what is the average costs in each category
--- what is the total revenue generated for each category
--- find total revenue generated by each customer
--- what is the distribution of sold items accross countries

select country,count(customer_id) as total_customers from gold.dim_customers
group by country
order by country;

select gender,count(customer_id) as total_customers from gold.dim_customers
group by gender
order by gender;

select category, count(product_number) total_products from gold.dim_products
group by category
order by category;

select category, avg(cost) as avg_cost from gold.dim_products
group by category
order by category;

select dp.category,sum(fs.sales_amount) as total_revenue from gold.fact_sales fs
left join gold.dim_products dp
on fs.product_key = dp.product_key
group by dp.category;

select dc.customer_number,dc.first_name,dc.last_name, sum(fs.sales_amount) as total_revenue from gold.fact_sales fs
left join gold.dim_customers dc
on fs.customer_key = dc.customer_key
group by dc.customer_number,dc.first_name,dc.last_name order by sum(fs.sales_amount) desc;

select top 5 * from gold.fact_sales;
select top 5 * from gold.dim_customers;

select  dc.country, sum(fs.quantity)  as distribution_of_items from gold.fact_sales fs
left join gold.dim_customers dc
on fs.customer_key = dc.customer_key
group by dc.country order by dc.country;
